!************************************
!*** constitutive testing module
!*** writes isoerror maps
!************************************
PROGRAM teste
  INCLUDE "simpar.inc"
  INTEGER,PARAMETER::NMA=100
  REAL(8)::OLDTEMPERATURE,NEWTEMPERATURE
  REAL(8),DIMENSION(NMA)::PSP,PRP,VAROLD,VAR,VAROLD_SAVE
  LOGICAL::TOTALLAGRANGIAN,PLANESTRESS
  REAL(8),DIMENSION(4)::RELATIVESTRAIN,EQUILIBRIUMSTRESS,OLDBACKSTRESS,NEWBACKSTRESS,OLDSTRAIN,NEWSTRAIN,OLDSTRAIN_SAVE,OLDSTRESS,NEWSTRESS
  REAL(8),DIMENSION(6)::OLD6STRESS,NEW6STRESS,OLD6STRESS_SAVE,STRAIN
  REAL(8),DIMENSION(3,3)::OLDGRAD,NEWGRAD,PROPOSEDGRAD,OLDFRAME,NEWFRAME,OLDGRAD_SAVE,OLDFRAME_SAVE,GTEMP,STRETCH,ROTATION
  REAL(8)::LENGTH
  REAL(8)::DHEATTEMPERATURE
  REAL(8),DIMENSION(3,200000)::XC
  REAL(8),DIMENSION(4)::DHEATDSTRAIN,DSTRESSDTEMPERATURE
  REAL(8),DIMENSION(4,4)::DSTRESSDSTRAIN,dstressdstrain1
!******************
!*** initialization
!******************
  IELEM=1
  IGAUS=1
  IEQIT=1000
  TOTALLAGRANGIAN=.FALSE.
  PLANESTRESS=.FALSE.
  IYIELD=1
  VAROLD=0.0D00
  VAR=0.0D00
  LENGTH=1.0D00
  TIME=0.0D00
  DTIME=1.0D-3
  NVOIGT=4
  NDI=3
  PRP=0.0D00
  PSP=0.0D00
  LOADMODE=1
  PRP(1)=5.2d3!1.0D00
  PRP(2)=0.35d00!0.33D00
  PRP(3)=200.0d00!1.0D00
  ALLOCATE(gphist(10,10,10,2))
  gphist=0.0d00
!***********************************
!*** ASKS WHAT IS THE INITIAL STRESS
!***********************************
  OLDSTRESS=0.0D00
  WRITE(*,*)"WHAT IS THE INITIAL STRESS?"
  WRITE(*,*)" S 11 "
  READ(*,*)OLDSTRESS(1)
  WRITE(*,*)" S 22 "
  READ(*,*)OLDSTRESS(2)
  WRITE(*,*)" S 12 "
  READ(*,*)OLDSTRESS(4)
  CALL TANGELAST(.FALSE.,3,4,PRP,DSTRESSDSTRAIN)
  CALL INVmat(4,DET,DSTRESSDSTRAIN,DSTRESSDSTRAIN1,.FALSE.)
  CALL matrixvectorproduct(4,4,DSTRESSDSTRAIN1,OLDSTRESS,OLDSTRAIN)
  WRITE(*,*)"STRAIN=",OLDSTRAIN
  WRITE(*,"(A)")" SELECT WHICH CASE YOU WANT (0-APPROX, 1-EXACT, 2-COMPARE) "
  READ(*,*)IEXACT
!*** fileprovidechannel
  IU=fileprovidechannel()
  IF(IEXACT.EQ.0)THEN
     OPEN(UNIT=IU,FILE="STRESSES.TXT",STATUS="UNKNOWN")
  ELSEIF(IEXACT.EQ.1)THEN
     OPEN(UNIT=IU,FILE="STRESSESEXACT.TXT",STATUS="UNKNOWN")
  ELSEIF(IEXACT.EQ.2)THEN
     OPEN(UNIT=IU,FILE="STRESSESCOMPARE.TXT",STATUS="UNKNOWN")     
  END IF
!*** MVALS
  MVALS=60
  MVALM=-MVALS
!  FMAX=0.00628027904754!!0.00209779961838!0.25D00
  EMAX=0.075d00!1.8000D00
  IF(IEXACT.EQ.0)THEN
     icount=0
     rtot=0.0d00
     DO I=MVALM,MVALS
        E11=1.0D00*I*EMAX/MVALS
        DO J=MVALM,MVALS
           icount=icount+1
           E22=1.0D00*J*EMAX/MVALS
           RELATIVESTRAIN(1)=E11
           RELATIVESTRAIN(2)=E22
           RELATIVESTRAIN(3)=0.0D00
           RELATIVESTRAIN(4)=0.0D00
           X=RELATIVESTRAIN(1)/OLDSTRAIN(1)
           Y=RELATIVESTRAIN(2)/OLDSTRAIN(2)
           NEWSTRESS=OLDSTRESS
!!           CALL PLA_MULTIPLE(IERR,LENGTH,IYIELD,IGAUS,IELEM,PLANESTRESS,OLDT,rNEWT,RELATIVESTRAIN,NEWSTRESS,TIME,DTIME,NVOIGT,PRP,VAROLD,VAR,reff,DSTRESSDSTRAIN)
           rtot=MAX(rtot,reff)
!           WRITE(IU,"(9E17.9)")X,Y,NEWSTRESS(1:4),VAR(5),VAR(1)
           X=OLDSTRAIN(1)+RELATIVESTRAIN(1)
           Y=OLDSTRAIN(2)+RELATIVESTRAIN(2)
           WRITE(IU,"(8E17.9)")X,Y,var(1)!VAR(5),VAR(1)
        END DO
     END DO
     CLOSE(IU)
!     WRITE(*,*)"rtot=",rtot
!     READ(*,*)
  ELSEIF(IEXACT.EQ.1)THEN
     NEWSTRESS=OLDSTRESS
     DO I=1,MVALS
        E11=1.0D00*I*EMAX/MVALS
        DO J=1,MVALS
           E22=1.0D00*J*EMAX/MVALS
           MEXACT=30!MAX(I,J)
           NEWSTRESS=OLDSTRESS
           VAROLD=0.0D00
           DO IMM=1,MEXACT
              RELATIVESTRAIN(1)=E11*(1.0d00*IMM)/MEXACT
              RELATIVESTRAIN(2)=E22*(1.0d00*IMM)/MEXACT
              RELATIVESTRAIN(3)=0.0D00
              RELATIVESTRAIN(4)=0.0D00
!!              CALL PLA_MULTIPLE(IERR,LENGTH,IYIELD,IGAUS,IELEM,PLANESTRESS,oldt,rnewt,RELATIVESTRAIN,NEWSTRESS,TIME,DTIME,NVOIGT,PRP,VAROLD,VAR,reff,DSTRESSDSTRAIN)
              VAROLD=VAR
           END DO
           X=RELATIVESTRAIN(1)/OLDSTRAIN(1)
           Y=RELATIVESTRAIN(2)/OLDSTRAIN(2)
           WRITE(IU,"(6E17.9)")X,Y,NEWSTRESS(1:4)
        END DO
     END DO
     CLOSE(IU)
  ELSE
     OPEN(UNIT=11,FILE="STRESSES.TXT",STATUS="UNKNOWN")
     OPEN(UNIT=12,FILE="STRESSESEXACT.TXT",STATUS="UNKNOWN")
     IK=0
     DO I=1,MVALS
        DO J=1,MVALS
           IK=IK+1
!*** DEFORMATION GRADIENT
           READ(11,*)RX,RY,S11A,S22A,S33A,S12A
           READ(12,*)RX,RY,S11E,S22E,S33E,S12E
           RTOP=SQRT((S11E-S11A)**2+(S22E-S22A)**2+(S12E-S12A)**2)
           RBOT=SQRT(S11E**2+S22E**2+S33E**2+S12E**2)
           IF(rbot.GT.epsmach())THEN
              XC(1,IK)=RX
              XC(2,IK)=RY
              XC(3,IK)=RTOP/RBOT                   
              WRITE(IU,"(5E17.9)")RX,RY,RTOP/RBOT
           ELSE
              XC(1,IK)=RX
              XC(2,IK)=RY
              XC(3,IK)=0.0d00
              WRITE(IU,"(5E17.9)")RX,RY,0.0d00
           END IF          
        END DO
     END DO
     NC=(MVALS+1)**2
     CALL OUTPUTENSIGHT(NC,XC)
     CLOSE(IU)       
  END IF
!*** CALLS
END PROGRAM TESTE
!
SUBROUTINE outputensight(nc,xc)
  USE OVERALL
  REAL(8),DIMENSION(3,*)::xc
  REAL(8)::apara,bpara
  LOGICAL::HASTHICK,ifparaview
  REAL(8),DIMENSION(:,:),ALLOCATABLE::SCALAR,ESCALAR
  REAL(8),DIMENSION(:,:,:),ALLOCATABLE::VECTOR,EVECTOR,TENS,ETENSOR
  CHARACTER(30),DIMENSION(:),ALLOCATABLE::CSCALAR,CESCALAR,CVECTOR,CEVECTOR,CTENSOR,CETENSOR
  INTEGER,DIMENSION(:),ALLOCATABLE::NELPR,NCNOS
!******************************
  REAL(8),DIMENSION(6)::COO
  REAL(8),DIMENSION(MVPE)::COE
  REAL(8),DIMENSION(MVPG)::COV
  REAL(8),DIMENSION(2,6)::COO2
  REAL(8),DIMENSION(2,MVPE)::COE2
  REAL(8),DIMENSION(2,MVPG)::COV2
  CHARACTER(6),DIMENSION(:),ALLOCATABLE::NAMES
  nscalar=1
  nescalar=0
  nvector=0
  nevector=0
  ntensor=0
  netensor=0
  NNO=NC
  NEL=NC
!*** ALLOCATES THE QUANTITIES
  CALL allocsafe(MAX(1,NSCALAR),NNO,SCALAR)
  CALL allocsafe(MAX(1,NESCALAR),NEL,ESCALAR)
  CALL allocsafe(3,MAX(1,NVECTOR),NNO,VECTOR)
  CALL allocsafe(3,MAX(1,NEVECTOR),NEL,EVECTOR)
  CALL allocsafe(6,MAX(1,NTENSOR),NNO,TENS)
  CALL allocsafe(6,MAX(1,NETENSOR),NEL,ETENSOR)
  CALL allocsafe(MAX(1,NSCALAR),CSCALAR)
  CALL allocsafe(MAX(1,NESCALAR),CESCALAR)
  CALL allocsafe(MAX(1,NVECTOR),CVECTOR)
  CALL allocsafe(MAX(1,NEVECTOR),CEVECTOR)
  CALL allocsafe(MAX(1,NTENSOR),CTENSOR)
  CALL allocsafe(MAX(1,NETENSOR),CETENSOR)
!**** fill what lacks
  cscalar(1)="Error"
!*** at the nodes
  DO ino=1,nc
     scalar(1,ino)=xc(3,ino)
  END DO
!*** PROVIDES ADDITIONAL REQUIRED QUANTITIES
  CALL allocsafe(nel,nelpr)
  DO iel=1,Nc
     nelpr(iel)=1!nelpre(iel)
     IF(itypoutput.EQ.0.AND.nelpr(iel).EQ.1)nelpr(iel)=0
  END DO
  CALL allocsafe(ntel,ncnos)
  DO I=1,NTEL
     ncnos(i)=nnosc(i)
  END DO
  CALL allocsafe(ntel,names)
  DO I=1,NTEL
     NAMES(I)=NOMES(I)
  END DO
!*** CALLS THE ENSIGHT OUTPUT ROUTINE
  ifparaview=.FALSE.
  nomef="merda"
  iouts=0
  CALL fileoutputensight_BIN(&
       Iouts,NOMEF, &
       NNO,xc(1:3,1:nc), &
       NEL, &
       NSCALAR,NVECTOR,NTENSOR, &
       CSCALAR,CVECTOR,CTENSOR, &
       SCALAR,VECTOR,TENS, &
       NESCALAR,NEVECTOR,NETENSOR, &
       CESCALAR,CEVECTOR,CETENSOR, &
       ESCALAR,EVECTOR,ETENSOR,NAMES,NELPR,NCNOS,ELNI,ELNO,ifparaview)
  iouts=iouts+1
END SUBROUTINE OUTPUTENSIGHT

